#!/bin/bash
#
# Copyright (C) 2015-2016 Pascal Cadotte Michaud
#
# This hook checks if there is a copyright in the each file included
# in this commit.
#
# If there is a copyright line, it checks if the current year is present.

current_year=$(date +"%Y")
files_to_check=$(git diff --cached --name-only --diff-filter=MA)
fail=0

for filename in $files_to_check
do
    grep -Poq "(:c|C)opyright.*${current_year}" <(git show :${filename})
    if [[ $? -ne 0 ]]; then
      echo "$filename has an outdated copyright date"
      fail=1
    fi
done

if [[ $fail -eq 0 ]]; then
    exit 0
fi

echo 'Commit aborted'

exit 1
