#!/bin/bash
#
# Copyright (C) 2015 Pascal Cadotte Michaud
#
# This hook checks if there is a copyright in the each file included
# in this commit.
#
# If there is a copyright line, it checks if the current year is present.

current_year=$(date +"%Y")
files_to_check=$(git diff --cached --name-only --diff-filter=MA)
fail=0

for filename in $files_to_check
do
    grep -i 'copyright' -m1 <(git show :$filename) | grep -v $current_year >> /dev/null
    if [[ $? -ne 1 ]]; then
      echo "$filename as an outdated copyright date"
      fail=1
    fi
done

if [[ $fail -eq 0 ]]; then
    exit 0
fi

echo 'Commit aborted'

exit 1
